version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-management-api
    environment:
      DATABASE_URL: 'postgresql://schedule-management-db:a1a2a3a4@postgres:5432/schedule_db'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:prod
      "

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: schedule-management-db
      POSTGRES_PASSWORD: a1a2a3a4
      POSTGRES_DB: schedule_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
